# Generated by Django 6.0.3 on 2026-04-15 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_one', to=settings.AUTH_USER_MODEL)),
                ('two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Par',
                'verbose_name_plural': 'Pares',
            },
        ),
    ]
