# Generated by Django 6.0.3 on 2026-04-16 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('critic', models.TextField()),
                ('critic_level', models.PositiveSmallIntegerField(default=1)),
                ('compliment', models.TextField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_reporter', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório diário',
                'verbose_name_plural': 'Relatórios diários',
                'ordering': ['-created_at'],
            },
        ),
    ]
