# Generated by Django 6.0.3 on 2026-04-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'default_permissions': ('add', 'view'), 'ordering': ['-created_at'], 'verbose_name': 'Relatório diário', 'verbose_name_plural': 'Relatórios diários'},
        ),
    ]
