events {}

http {
    upstream django_app {
        server app:8000;
    }

    server {
        listen 80;
        server_name _;

        client_max_body_size 20m;

        location /static/ {
            alias /static/app/;
            autoindex off;
            expires 7d;
            add_header Cache-Control "public, max-age=604800";
        }

        location /media/ {
            alias /media/;
            autoindex off;
            expires 1d;
            add_header Cache-Control "public, max-age=86400";
        }

        location / {
            proxy_pass http://django_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }
    }
}
